version: "2"

linters:
  # please, do not use `default: all`: inverted configuration with all linters
  # and disabled linters is not scalable during updates of golangci-lint.
  default: none
  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - exhaustive
    - bidichk
    - gocritic
    - govet
    - ineffassign
    #- nolintlint
    - staticcheck
    - unconvert
    - usestdlibvars
    - unparam
    - unused
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - revive
    - forbidigo
    - makezero
  settings:
    errcheck:
      exclude-functions:
        - fmt:.*
        - io/ioutil:^Read.*

    gocritic:
      disabled-checks:
        - exitAfterDefer

    forbidigo:
      # Forbid the following identifiers
      forbid:
        - pattern: ^fmt\.Errorf$ # consider errors.Errorf in github.com/pkg/errors
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: "Error return value of .((os.)?std(out|err)..*|.*Close|.*Seek|.*Flush|os.Remove(All)?|.*print(f|ln)?|os.(Un)?Setenv). is not check"
    paths:
      - db
      - cmd/api-generator
      - internal/encryption

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Mrs4s/go-cqhttp
  exclusions:
    paths:
      - db
      - cmd/api-generator
      - internal/encryption

run:
  # default concurrency is an available CPU number.
  # concurrency: 4 # explicitly omit this value to fully utilize available resources.
  timeout: 5m
  issues-exit-code: 1
  tests: true

# output configuration options
output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
      colors: true

issues:
  # Fix found issues (if it's supported by the linter)
  fix: true
